image:
  repository: tccr.io/truecharts/postgresql
  pullPolicy: IfNotPresent
  tag: 14.7.0@sha256:9a9097005c47417ba785fdc0e4ced26937106234abfce83da36ce6accdceca60
manifestManager:
  enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        targetPort: 5432
        port: 5432

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PG_SECURITY_ADMIN_USER: "admin"
            PG_SECURITY_ADMIN_PASSWORD: "postgres"
            PG_SECURITY_DB_USER: "admin"
            PG_SECURITY_DB_PASSWORD: "postgres"
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false

persistence:
  data:
    enabled: true
    mountPath: "/var/lib/postgresql/data"

portal:
  open:
    enabled: false

cnpg:
  main:
    enabled: false
    primary: true
    # -- number of instances for both postgres and pgbouncer
    instances: 2
    database: "app"
    user: "app"
    # password:
    # superUserPassword:
    # -- change to supervised to disable unsupervised updates
    # Example of rolling update strategy:
    # - unsupervised: automated update of the primary once all
    #                 replicas have been upgraded (default)
    # - supervised: requires manual supervision to perform
    #               the switchover of the primary
    primaryUpdateStrategy: unsupervised
    # -- enable to create extra pgbouncer for readonly access
    acceptRO: false
    # -- storage size for the two pvc's per instance
    storage:
      size: "256Gi"
      walsize: "256Gi"
    pooler:
      instances: 2
    # -- set to enable prometheus metrics
    monitoring:
      enablePodMonitor: true
    # -- contains credentials and urls output by generator
    creds: {}
